/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html"
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f3f3fe",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#ffeedd",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#0053db",
        "secondary": "#006c49",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#eeefff",
        "surface-bright": "#faf8ff",
        "on-secondary-fixed-variant": "#005236",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container-highest": "#e1e2ed",
        "on-primary-fixed": "#00174b",
        "error": "#ba1a1a",
        "background": "#faf8ff",
        "secondary-container": "#6cf8bb",
        "on-error-container": "#93000a",
        "primary-fixed": "#dbe1ff",
        "on-error": "#ffffff",
        "on-surface-variant": "#434655",
        "primary-container": "#2563eb",
        "inverse-surface": "#2e3039",
        "on-secondary-fixed": "#002113",
        "tertiary-container": "#996100",
        "tertiary": "#784b00",
        "on-primary": "#ffffff",
        "surface": "#faf8ff",
        "primary-fixed-dim": "#b4c5ff",
        "inverse-on-surface": "#f0f0fb",
        "surface-dim": "#d9d9e5",
        "secondary-fixed": "#6ffbbe",
        "surface-container": "#ededf9",
        "secondary-fixed-dim": "#4edea3",
        "outline": "#737686",
        "surface-container-high": "#e7e7f3",
        "inverse-primary": "#b4c5ff",
        "on-surface": "#191b23",
        "primary": "#004ac6",
        "on-background": "#191b23",
        "on-secondary": "#ffffff",
        "surface-variant": "#e1e2ed",
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary-container": "#00714d",
        "tertiary-fixed-dim": "#ffb95f",
        "tertiary-fixed": "#ffddb8",
        "outline-variant": "#c3c6d7"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "md": "24px",
        "xs": "8px",
        "xl": "48px",
        "base": "4px",
        "gutter": "24px",
        "sm": "16px",
        "lg": "32px",
        "container-max": "1440px"
      },
      fontFamily: {
        "label-caps": ["Albert Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-md": ["Albert Sans"],
        "body-sm": ["Albert Sans"],
        "data-mono": ["JetBrains Mono"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Albert Sans"],
        "headline-md": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "label-caps": ["11px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "data-mono": ["13px", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
